apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test-config
data: 
  nginx.index: |
      <!DOCTYPE html>
      <html>
      <head>
      <title>TEST PIPELINE</title>
      <style>
      html { color-scheme: light dark; }
      body { width: 35em; margin: 0 auto;
      font-family: Tahoma, Verdana, Arial, sans-serif; }
      </style>
      </head>
      <body>
      <h1>-------------------------</h1>
      <p>--------------------------</p>
      <p><em>POWERED BY NGINX.</em></p>
      </body>
      </html>
---