apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx-test
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx-test
          image: nginx:1.20.2
          ports:
           - containerPort: 80
          volumeMounts:
            - name: nginx-test-index
              mountPath: /usr/share/nginx/html/index.html
              subPath: nginx.index
      volumes:
        - name: nginx-test-index
          configMap: 
            name: nginx-test-config